// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }















import type { Metadata, Viewport } from "next";
import "./globals.css";
import { SITE, CONTACT } from "@/lib/constants";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ScrollReveal from "@/components/ui/ScrollReveal";

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} — ${SITE.tagline}`,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  keywords: [
    "corn silage export Pakistan",
    "silage supplier Pakistan",
    "livestock feed export",
    "corn silage bulk export",
    "agricultural exports Pakistan",
    "halal certified silage",
    "corn silage Middle East",
    "corn silage Europe",
    "Pakistan agri export",
    "fermented corn feed",
  ],
  authors: [{ name: SITE.name, url: SITE.url }],
  creator: SITE.name,
  publisher: SITE.name,
  formatDetection: { email: false, address: false, telephone: false },
  openGraph: {
    type:        "website",
    locale:      "en_US",
    url:         SITE.url,
    siteName:    SITE.name,
    title:       `${SITE.name} — ${SITE.tagline}`,
    description: SITE.description,
    images: [{ url: SITE.ogImage, width: 1200, height: 630, alt: SITE.name }],
  },
  twitter: {
    card:        "summary_large_image",
    title:       `${SITE.name} — ${SITE.tagline}`,
    description: SITE.description,
    images:      [SITE.ogImage],
  },
  robots: {
    index:     true,
    follow:    true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  alternates: { canonical: SITE.url },
};

export const viewport: Viewport = {
  themeColor: "#1A4D2E",
  width:      "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Structured Data — Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name:    SITE.name,
              url:     SITE.url,
              logo:    `${SITE.url}${SITE.logo}`,
              contactPoint: {
                "@type":       "ContactPoint",
                telephone:     CONTACT.phoneRaw,
                contactType:   "sales",
                availableLanguage: ["English", "Urdu"],
              },
              address: {
                "@type":           "PostalAddress",
                streetAddress:     CONTACT.address.street,
                addressLocality:   CONTACT.address.city,
                addressRegion:     CONTACT.address.province,
                addressCountry:    "PK",
              },
              sameAs: [],
            }),
          }}
        />
      </head>
      <body>
        <ScrollReveal />
        <Navbar />
        <main id="main-content" tabIndex={-1}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
